import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Provider } from "@/utils/lib/provider/provider";
import { Bounce, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Loading } from "./components/loading/loading.component";
import { ThemeProvider } from "@/context/context";
import React from "react";
import { HeaderWithShoppingCart } from "./layout/header-with-shopping-cart/header-with-shopping-cart.layout";

const poppins = Poppins({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cartVisibility = false;
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-background`}>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover={false}
          theme="colored"
          transition={Bounce}
          className="z-50"
        />
        <Provider>
          <ThemeProvider>
            <React.Suspense fallback={<Loading />}>
              <HeaderWithShoppingCart />
              {children}
            </React.Suspense>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
};