import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Provider } from "@/utils/lib/provider/provider";
import { Loading } from "./components/loading/loading.component";
import { ThemeProvider } from "@/context/context";
import React from "react";
import { LayoutWrapper } from "./layout/layout-wrapper/layout-wrapper.layout";

const font = Roboto({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-background`}>
        <Provider>
          <ThemeProvider>
            <React.Suspense fallback={<Loading />}>
              <LayoutWrapper />
              {children}
            </React.Suspense>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
};